### ISSUE TITLE
🐛 thehaguetech.com gives ":( Application Error"

### ISSUE THREAD

**Issue by bartwr** [thehaguetech/thehaguetech-site#11]
**Describe the bug**
If I go to thehaguetech.com, I get an ":( Application Error"

**To Reproduce**
1. Go to https://www.thehaguetech.com
2. (Wait)

**Expected behavior**
The Hague Tech site shows up.

**Screenshots**
![image](https://user-images.githubusercontent.com/899234/67606833-dd2c7c00-f782-11e9-90bc-7c5e307a43de.png)

**Smartphone:**
Device + Browser

**Additional context**
The error shows up since [this](https://github.com/thehaguetech/thehaguetech-site/commit/70011d15ad49c9cdcca5dc97dcd75be77ed3146e) commit.

**Comment by bartwr** [comment]
These are the logs:

```log
2019-10-23T02:35:18.820233726Z > thehaguetech-site@0.1.0 start /home/site/wwwroot
2019-10-23T02:35:18.820240026Z > node ./node_modules/next/dist/bin/next build && NODE_ENV=production node api/server.js
2019-10-23T02:35:18.820244626Z
2019-10-23T02:35:22.317695814Z Creating an optimized production build ...
2019-10-23T02:35:22.336952454Z
2019-10-23T02:35:25.946729677Z > Build error occurred
2019-10-23T02:35:25.951567638Z SyntaxError: Cannot parse records: Unexpected end of JSON input while parsing near ''
2019-10-23T02:35:25.951598239Z     at JSON.parse (<anonymous>)
2019-10-23T02:35:25.951604939Z     at parseJson (/node_modules/json-parse-better-errors/index.js:7:17)
2019-10-23T02:35:25.951609539Z     at Array.inputFileSystem.readFile (/node_modules/webpack/lib/Compiler.js:490:21)
2019-10-23T02:35:25.951613939Z     at Storage.finished (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
2019-10-23T02:35:25.951618239Z     at provider (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
2019-10-23T02:35:25.951622740Z     at /node_modules/graceful-fs/graceful-fs.js:90:16
2019-10-23T02:35:25.951627140Z     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
2019-10-23T02:35:25.980719407Z npm ERR! code ELIFECYCLE
2019-10-23T02:35:25.982460965Z npm ERR! errno 1
2019-10-23T02:35:25.993407729Z npm ERR! thehaguetech-site@0.1.0 start: `node ./node_modules/next/dist/bin/next build && NODE_ENV=production node api/server.js`
2019-10-23T02:35:26.001239389Z npm ERR! Exit status 1
2019-10-23T02:35:26.001960813Z npm ERR!
2019-10-23T02:35:26.002684637Z npm ERR! Failed at the thehaguetech-site@0.1.0 start script.
2019-10-23T02:35:26.003385461Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-23T02:35:26.211381076Z
2019-10-23T02:35:26.212593117Z npm ERR! A complete log of this run can be found in:
2019-10-23T02:35:26.213642752Z npm ERR!     /root/.npm/_logs/2019-10-23T02_35_26_019Z-debug.log
```

> An NPM package seems to be the problem; it doesn't pass the build, even not at a rollback. ~peter-jvt

**Comment by bartwr** [comment]
We fixed this by moving the site to Heroku. #TODO Make the site work on Microsoft Azure platform again. This can be a new issue => This issue is solved,
